/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        light: {
          html: "#E34F26",
          css: "#1572B6",
          js: "#F7DF1E",
          ts: "#3178C6",
          react: "#61DAFB",
          tailwind: "#38B2AC",
          next: "#000000",
          node: "#339933",
          nest: "#E0234E",
          express: "#000000",
          mongodb: "#47A248",
          antd: "#1677FF",
          shadcn: "#0F172A",
          mui: "#007FFF",
          github: "#181717",
          api: "#0EA5E9",
          jwt: "#DC2626",
          responsive: "#8B5CF6",
          figma: "#F24E1E",
          scrum: "#14B8A6",
        },
        dark: {
          html: "#D65A31",
          css: "#1E3A8A",
          js: "#F4B500",
          ts: "#2A5B9F",
          react: "#2D9CDB",
          tailwind: "#2C7A7B",
          next: "#F4F4F4",
          node: "#215732",
          nest: "#A61B3E",
          express: "#F4F4F4",
          mongodb: "#3D6E40",
          antd: "#4096FF",
          shadcn: "#F8FAFC",
          mui: "#66B2FF",
          github: "#F4F4F4",
          api: "#38BDF8",
          jwt: "#EF4444",
          responsive: "#A78BFA",
          figma: "#FF7262",
          scrum: "#2DD4BF",
        },
        custom: {
          lightBg: "#f7fafc",
          lightBorder: "#cbd5e0",
          darkBg: "#2d3748",
          darkBorder: "#1a202c",
          hoverBlue: "#3182ce",
          antd: "#4096FF",
        },
      },
    },
    fontFamily: {
      main: ["Montserrat", "sans-serif"],
    },
  },
  plugins: [],
};
